name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1
      
    - name: Run unit tests
      run: zig build test
      
  end-to-end:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1
      
    - name: Build project
      run: zig build
      
    - name: Create config directory
      run: mkdir -p ~/.config/hyprshot-cloud
      
    - name: Create config file from secret
      run: echo '${{ secrets.S3_CONFIG_JSON }}' > ~/.config/hyprshot-cloud/config.json
      
    - name: Run end-to-end tests
      run: |
        # Create a test file
        echo "This is a test file for CI" > test-file.txt
        
        # Create a test bucket
        ./zig-out/bin/hyprshot-cloud create-bucket --bucket hyprshot-cloud-ci-test
        
        # Upload the test file
        ./zig-out/bin/hyprshot-cloud upload test-file.txt --bucket hyprshot-cloud-ci-test
        
        # List objects in the bucket and verify our file is there
        output=$(./zig-out/bin/hyprshot-cloud list-objects --bucket hyprshot-cloud-ci-test)
        if echo "$output" | grep -q "test-file.txt"; then
          echo "File found in bucket as expected"
        else
          echo "ERROR: File not found in bucket"
          exit 1
        fi
        
        # List buckets and verify our test bucket is there
        output=$(./zig-out/bin/hyprshot-cloud list-buckets)
        if echo "$output" | grep -q "hyprshot-cloud-ci-test"; then
          echo "Bucket found as expected"
        else
          echo "ERROR: Bucket not found"
          exit 1
        fi
        
        # Delete the test object
        ./zig-out/bin/hyprshot-cloud delete-object test-file.txt --bucket hyprshot-cloud-ci-test
        
        # Verify object was deleted
        output=$(./zig-out/bin/hyprshot-cloud list-objects --bucket hyprshot-cloud-ci-test)
        if echo "$output" | grep -q "test-file.txt"; then
          echo "ERROR: File still found in bucket after deletion"
          exit 1
        else
          echo "File successfully deleted from bucket"
        fi
        
        # Delete the test bucket
        ./zig-out/bin/hyprshot-cloud delete-bucket --bucket hyprshot-cloud-ci-test
        
        # Verify bucket was deleted
        output=$(./zig-out/bin/hyprshot-cloud list-buckets)
        if echo "$output" | grep -q "hyprshot-cloud-ci-test"; then
          echo "ERROR: Bucket still found after deletion"
          exit 1
        else
          echo "Bucket successfully deleted"
        fi
      
  build:
    needs: [test, end-to-end]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1
      
    - name: Build project
      run: zig build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hyprshot-cloud-${{ matrix.os }}
        path: zig-out/bin/
